spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tasks?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always
    include-binding-errors: on_param